### ISSUE TITLE
power xxx 的 hooks 里面，拿其他 storage 有点麻烦

### ISSUE THREAD

**Issue by vilicvane** [mufancom/makeflow-sdk#12]
- 第一个是没有传入 `powerApp`，直接外部引入容易产生循环依赖。
- 第二个是希望能直接从 hooks 里拿到类似 installationStorage, userStorage（如果可用）类似的。

**Comment by boenfu** [comment]
https://github.com/makeflow/makeflow-sdk/commit/0b851b8a31847ef03473c7b6d832a9ce574b9a7e
